[2024-03-09T22:08:40.178+0530] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sql_operator_dag.taskA scheduled__2024-03-08T00:00:00+00:00 [queued]>
[2024-03-09T22:08:40.184+0530] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sql_operator_dag.taskA scheduled__2024-03-08T00:00:00+00:00 [queued]>
[2024-03-09T22:08:40.184+0530] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-09T22:08:40.218+0530] {taskinstance.py:2214} INFO - Executing <Task(SqliteOperator): taskA> on 2024-03-08 00:00:00+00:00
[2024-03-09T22:08:40.221+0530] {standard_task_runner.py:60} INFO - Started process 48999 to run task
[2024-03-09T22:08:40.225+0530] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'sql_operator_dag', 'taskA', 'scheduled__2024-03-08T00:00:00+00:00', '--job-id', '94', '--raw', '--subdir', 'DAGS_FOLDER/execute_sql_pipeline.py', '--cfg-path', '/tmp/tmp61d2yj7t']
[2024-03-09T22:08:40.227+0530] {standard_task_runner.py:88} INFO - Job 94: Subtask taskA
[2024-03-09T22:08:40.289+0530] {task_command.py:423} INFO - Running <TaskInstance: sql_operator_dag.taskA scheduled__2024-03-08T00:00:00+00:00 [running]> on host BreakThrough.
[2024-03-09T22:08:40.381+0530] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='kai' AIRFLOW_CTX_DAG_ID='sql_operator_dag' AIRFLOW_CTX_TASK_ID='taskA' AIRFLOW_CTX_EXECUTION_DATE='2024-03-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-08T00:00:00+00:00'
[2024-03-09T22:08:40.382+0530] {sql.py:276} INFO - Executing: CREATE TABLE IF NOT EXISTS students (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT,
            age INTEGER NOTNULL, 
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            place TEXT
        )
[2024-03-09T22:08:40.386+0530] {base.py:83} INFO - Using connection ID 'my_sqlite_conn' for task execution.
[2024-03-09T22:08:40.414+0530] {base.py:83} INFO - Using connection ID 'my_sqlite_conn' for task execution.
[2024-03-09T22:08:40.414+0530] {sql.py:457} INFO - Running statement: CREATE TABLE IF NOT EXISTS students (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT,
            age INTEGER NOTNULL, 
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            place TEXT
        ), parameters: None
[2024-03-09T22:08:40.415+0530] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/kai/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/kai/.local/lib/python3.10/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
  File "/home/kai/.local/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 404, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/kai/.local/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 462, in _run_command
    cur.execute(sql_statement)
sqlite3.OperationalError: near "NOTNULL": syntax error
[2024-03-09T22:08:40.420+0530] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=sql_operator_dag, task_id=taskA, execution_date=20240308T000000, start_date=20240309T163840, end_date=20240309T163840
[2024-03-09T22:08:40.464+0530] {standard_task_runner.py:107} ERROR - Failed to execute job 94 for task taskA (near "NOTNULL": syntax error; 48999)
[2024-03-09T22:08:40.478+0530] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-09T22:08:40.490+0530] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
