[2024-03-10T09:00:49.849+0530] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_task_groups_edge_labels_dag.branch manual__2024-03-10T03:30:40.400692+00:00 [queued]>
[2024-03-10T09:00:49.855+0530] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_task_groups_edge_labels_dag.branch manual__2024-03-10T03:30:40.400692+00:00 [queued]>
[2024-03-10T09:00:49.855+0530] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-10T09:00:49.884+0530] {taskinstance.py:2214} INFO - Executing <Task(BranchPythonOperator): branch> on 2024-03-10 03:30:40.400692+00:00
[2024-03-10T09:00:49.887+0530] {standard_task_runner.py:60} INFO - Started process 112420 to run task
[2024-03-10T09:00:49.890+0530] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline_task_groups_edge_labels_dag', 'branch', 'manual__2024-03-10T03:30:40.400692+00:00', '--job-id', '145', '--raw', '--subdir', 'DAGS_FOLDER/execute_branching_task_group_edge_labels.py', '--cfg-path', '/tmp/tmpxzwyfp92']
[2024-03-10T09:00:49.893+0530] {standard_task_runner.py:88} INFO - Job 145: Subtask branch
[2024-03-10T09:00:49.951+0530] {task_command.py:423} INFO - Running <TaskInstance: pipeline_task_groups_edge_labels_dag.branch manual__2024-03-10T03:30:40.400692+00:00 [running]> on host BreakThrough.
[2024-03-10T09:00:50.029+0530] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='kai' AIRFLOW_CTX_DAG_ID='pipeline_task_groups_edge_labels_dag' AIRFLOW_CTX_TASK_ID='branch' AIRFLOW_CTX_EXECUTION_DATE='2024-03-10T03:30:40.400692+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-10T03:30:40.400692+00:00'
[2024-03-10T09:00:50.030+0530] {logging_mixin.py:188} INFO - branch
[2024-03-10T09:00:50.034+0530] {logging_mixin.py:188} INFO - filter_by_coverage
[2024-03-10T09:00:50.034+0530] {python.py:202} INFO - Done. Returned value was: filtering.filter_by_coverage
[2024-03-10T09:00:50.035+0530] {branch.py:35} INFO - Branch into filtering.filter_by_coverage
[2024-03-10T09:00:50.035+0530] {skipmixin.py:178} INFO - Following branch filtering.filter_by_coverage
[2024-03-10T09:00:50.038+0530] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/kai/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/kai/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 234, in execute
    return self.do_branch(context, super().execute(context))
  File "/home/kai/.local/lib/python3.10/site-packages/airflow/operators/branch.py", line 36, in do_branch
    self.skip_all_except(context["ti"], branches_to_execute)
  File "/home/kai/.local/lib/python3.10/site-packages/airflow/models/skipmixin.py", line 213, in skip_all_except
    raise AirflowException(
airflow.exceptions.AirflowException: 'branch_task_ids' must contain only valid task_ids. Invalid tasks found: {'filtering.filter_by_coverage'}.
[2024-03-10T09:00:50.040+0530] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=pipeline_task_groups_edge_labels_dag, task_id=branch, execution_date=20240310T033040, start_date=20240310T033049, end_date=20240310T033050
[2024-03-10T09:00:50.065+0530] {standard_task_runner.py:107} ERROR - Failed to execute job 145 for task branch ('branch_task_ids' must contain only valid task_ids. Invalid tasks found: {'filtering.filter_by_coverage'}.; 112420)
[2024-03-10T09:00:50.105+0530] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-10T09:00:50.132+0530] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
