[2024-03-10T09:03:08.105+0530] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_task_groups_edge_labels_dag.branch manual__2024-03-10T03:32:57.501669+00:00 [queued]>
[2024-03-10T09:03:08.111+0530] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_task_groups_edge_labels_dag.branch manual__2024-03-10T03:32:57.501669+00:00 [queued]>
[2024-03-10T09:03:08.111+0530] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-10T09:03:08.138+0530] {taskinstance.py:2214} INFO - Executing <Task(BranchPythonOperator): branch> on 2024-03-10 03:32:57.501669+00:00
[2024-03-10T09:03:08.141+0530] {standard_task_runner.py:60} INFO - Started process 113138 to run task
[2024-03-10T09:03:08.146+0530] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline_task_groups_edge_labels_dag', 'branch', 'manual__2024-03-10T03:32:57.501669+00:00', '--job-id', '148', '--raw', '--subdir', 'DAGS_FOLDER/execute_branching_task_group_edge_labels.py', '--cfg-path', '/tmp/tmprzvqprur']
[2024-03-10T09:03:08.148+0530] {standard_task_runner.py:88} INFO - Job 148: Subtask branch
[2024-03-10T09:03:08.199+0530] {task_command.py:423} INFO - Running <TaskInstance: pipeline_task_groups_edge_labels_dag.branch manual__2024-03-10T03:32:57.501669+00:00 [running]> on host BreakThrough.
[2024-03-10T09:03:08.286+0530] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='kai' AIRFLOW_CTX_DAG_ID='pipeline_task_groups_edge_labels_dag' AIRFLOW_CTX_TASK_ID='branch' AIRFLOW_CTX_EXECUTION_DATE='2024-03-10T03:32:57.501669+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-10T03:32:57.501669+00:00'
[2024-03-10T09:03:08.286+0530] {logging_mixin.py:188} INFO - branch
[2024-03-10T09:03:08.290+0530] {logging_mixin.py:188} INFO - filter_by_coverage
[2024-03-10T09:03:08.291+0530] {python.py:202} INFO - Done. Returned value was: filtering.filter_by_coverage
[2024-03-10T09:03:08.291+0530] {branch.py:35} INFO - Branch into filtering.filter_by_coverage
[2024-03-10T09:03:08.291+0530] {skipmixin.py:178} INFO - Following branch filtering.filter_by_coverage
[2024-03-10T09:03:08.295+0530] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/kai/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/kai/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 234, in execute
    return self.do_branch(context, super().execute(context))
  File "/home/kai/.local/lib/python3.10/site-packages/airflow/operators/branch.py", line 36, in do_branch
    self.skip_all_except(context["ti"], branches_to_execute)
  File "/home/kai/.local/lib/python3.10/site-packages/airflow/models/skipmixin.py", line 213, in skip_all_except
    raise AirflowException(
airflow.exceptions.AirflowException: 'branch_task_ids' must contain only valid task_ids. Invalid tasks found: {'filtering.filter_by_coverage'}.
[2024-03-10T09:03:08.297+0530] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=pipeline_task_groups_edge_labels_dag, task_id=branch, execution_date=20240310T033257, start_date=20240310T033308, end_date=20240310T033308
[2024-03-10T09:03:08.321+0530] {standard_task_runner.py:107} ERROR - Failed to execute job 148 for task branch ('branch_task_ids' must contain only valid task_ids. Invalid tasks found: {'filtering.filter_by_coverage'}.; 113138)
[2024-03-10T09:03:08.359+0530] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-10T09:03:08.385+0530] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
